coverageLab/urls.py
from django.contrib import admin
from django.urls import path, include
from lab_6.views import home as homes
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab_6/', include('lab_6.urls', namespace = 'lab_6')),
    path('', homes, name='home'),
    url(r'^lab_6/auth/', include('social_django.urls', namespace='social')),

]

lab_6/urls.py
from .views import *
from django.urls import path, include, re_path
from django.contrib.auth import views
from django.conf.urls import url

app_name='lab_6'
urlpatterns = [
    path('', home, name='home'),
    path('profile', profile, name='profile'),
    path('get_json/variable=<str:variable>', get_json, name='get_json'),
    path('books', books, name='books'),
    path('login_page', login_page, name='login_page'),
    path('check_email', check_email, name='check_email'),
    path('subscriber_add', subscriber_add, name='subscriber_add'),
    path('get_subscriber', get_subscriber, name="get_subscriber"),
    path('del_subscriber', del_subscriber, name='del_subscriber'),
    path('choice', choice, name='choice'),
    path('logingOut', logingOut, name='logingOut'),
    path('like', like, name = 'like'),
    path('get_like', get_like, name ='get_like'),
    path('unlike', unlike, name = 'unlike')
]

lab_6/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Activity(models.Model):
    title = models.CharField(max_length = 50, null = True)
    desc = models.CharField(max_length = 300, null = True)
    date = models.DateTimeField(default=timezone.now)

class Subscriber(models.Model):
    nama_pendaftar = models.CharField(max_length = 50)
    email_pendaftar = models.CharField(max_length = 200)
    password_pendaftar = models.CharField(max_length = 32)

lab_6/forms.py
from django import forms
from .models import Activity, Subscriber

class Add_Activity(forms.Form):
    error_messages = {
    'required': 'Please type',
    }

    title_attrs = {
    'type' : 'text',
    'class': "form-group col-md-12",
    'placeholder': 'Masukin nama',
    'id' : 'Id_title'
    }

    description_attrs = {
    'type': 'text',
    'class': "form-group col-md-12",
    'placeholder': 'Apa yang sedang kamu pikirkan?',
    'id' : 'id_description'
    }

    title = forms.CharField(label='Nama', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    desc = forms.CharField(label='Status', required=True, max_length = 200, widget=forms.TextInput(attrs=description_attrs))

class Subscriber_Form(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['nama_pendaftar', 'email_pendaftar', 'password_pendaftar']

    nama_pendaftar = forms.CharField(label='Nama', required=True, max_length = 50, widget=forms.TextInput(attrs={'class':'form-control', 'id':'nameForm'}))
    email_pendaftar = forms.CharField(label='Email', required=True, max_length = 200, widget=forms.TextInput(attrs={'class':'form-control', 'type':'email', 'id':'emailForm'}))
    password_pendaftar = forms.CharField(label='Password', max_length=32, widget=forms.PasswordInput(attrs={'class':'form-control', 'id':'passwordForm'}))

    def clean(self):
        cleaned_data = super(Subscriber_Form, self).clean()
        email_dicari = cleaned_data.get('email_pendaftar')
        email_in_db = Subscriber.objects.filter(email_pendaftar=email_dicari)

        if email_in_db.exists():
            self.add_error('email_pendaftar', 'This email has been taken.')

lab_6/views.py
from django.shortcuts import render, redirect
import requests
from django.http import HttpResponse, JsonResponse
from .models import Activity, Subscriber
from .forms import Add_Activity, Subscriber_Form
from django.core.validators import validate_email
from django.core import serializers
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt

def home(request):
    form = Add_Activity(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        status = Activity()
        status.title = form.cleaned_data['title']
        status.desc = form.cleaned_data['desc']
        status.save()
        html = 'index.html'
        return redirect('lab_6:home')

    else:
        activity = Activity.objects.all()
        form = Add_Activity()
        response = {'form' : form, 'activity': activity}
        return render(request, 'index.html', response)

def profile(request):
     return render(request, 'profile.html')


def get_json(request, variable='quilting'):
    raw_data = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + variable).json()
    items_ =[]
    print(raw_data)
    for info in raw_data['items']:
        data = {}
        data['image'] = info['volumeInfo']['imageLinks']['thumbnail']
        data['title'] = info['volumeInfo']['title']
        if ('authors' in info['volumeInfo']):
            data['author'] = " and ".join(info['volumeInfo']['authors'])
        else:
            data['author'] = '-'
        if ('publishedDate' in info['volumeInfo']):
            data['publishedDate'] = info['volumeInfo']["publishedDate"]
        else:
            data['publishedDate'] = "Unknown"
        items_.append(data)
    return JsonResponse({"data" :items_})

def subscriber_add(request):
    if request.method == 'POST':
        print('masuk kesini ga sih?')
        subscribe = Subscriber(
            nama_pendaftar = request.POST['name'],
            email_pendaftar = request.POST['email'],
            password_pendaftar = request.POST['password']
        )
        subscribe.save()
        return JsonResponse({
            'message':'Subscribe Success!'
        }, status = 200)
    else:
        return JsonResponse({
            'message':"There's no GET method here"
        }, status = 403)

def login_page(request):
    response={}
    response['form'] = Subscriber_Form
    return render(request, 'login.html', response)

def check_email(request):
    print('stdouhghj')
    try:
        print('masuk try')
        print(request.POST["email"])
        validate_email(request.POST["email"])
    except:
        print('masuk except')
        return JsonResponse({
            'message':'Email format is wrong!',
            'status':'fail'
        })

    exist = Subscriber.objects.filter(email_pendaftar=request.POST['email'])

    if exist:
        return JsonResponse({
            'message':'Email already exist',
            'status':'fail'
        })

    return JsonResponse({
        'message':'Email can be used',
        'status':'success'
    })

def get_subscriber(request):
    if request.method == 'GET':
        print("masuk ke get_subsciber")
        lst_subscriber = serializers.serialize('json', Subscriber.objects.all())
        response = lst_subscriber

    else:
        response['message'] = 'Method POST not ALLOWED HERE'
    return HttpResponse(response, content_type='application/json')

def del_subscriber(request):
    if request.method == 'POST':
        print("masuk ke del_subscriber")
        theOne = Subscriber.objects.get(pk=request.POST.get('pk'))
        print(theOne)
        theOne.delete()
        response['message'] = "success"
    else:
        response['message'] = "Method GET not allowed here"
    return JsonResponse(response)

def books(request):
    if request.user.is_authenticated :
        if "like" not in request.session:
            request.session["fullname"]=request.user.first_name+" "+request.user.last_name
            request.session["username"]=request.user.username
            request.session["email"] = request.user.email
            request.session["sessionid"]=request.session.session_key
            request.session["like"]=[]

    return render(request, 'books.html')

def choice(request):
    return render(request, 'choice.html')

def logingOut(request):
    logout(request)
    return redirect('lab_6:books')

@csrf_exempt
def like(request):
    if(request.method=="POST"):
        lst = request.session["like"]
        if request.POST["id"] not in lst :
            lst.append(request.POST["id"])
        print(request.session["sessionid"])
        print(request.session["like"])
        request.session["like"]= lst
        response["message"]=len(lst)
        return JsonResponse(response)
    else:
        return HttpResponse("GET Method not allowed")

@csrf_exempt
def unlike(request):
    if(request.method=="POST"):
        lst = request.session["like"]
        if request.POST["id"] in lst :
            lst.remove(request.POST["id"])
        print(request.session["sessionid"])
        print(request.session["like"])
        request.session["like"]= lst
        response["message"]=len(lst)
        return JsonResponse(response)
    else:
        return HttpResponse("GET Method not allowed")


def get_like(request):
    if request.user.is_authenticated :
        if(request.method=="GET"):
            if request.session["like"] is not None:
                response["message"] = request.session["like"]
        else:
            response["message"] = "NOT ALLOWED"
    else:
        response["message"] = ""
    return JsonResponse(response)

lab_6/templates/books.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/coverageLab.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <title id="Judul">Animusity | Books</title>
  </head>


  <body>
    <section class="authenticator">
      <div class="container">
        {% if user.is_authenticated %}
        <p class="display-4">Hello, {{ user.username }}</p>
        <a href="{% url 'lab_6:logingOut' %}" style="color: black;">Logout</a>
	      {% else %}
        <a class="lead" href="{% url 'lab_6:choice' %}">Log in</a>
	      {% endif %}
      </div>
    </section>



    <section class="search bar">
      <div>
        <div class="col-auto">
          <div class="input-group input-group-sm mb-3">
            <input type="search" class="form-control" aria-label="Small" name = "pencarian" placeholder="Cari disini" aria-describedby="inputGroup-sizing-sm">
          </div>
          <div class="container text-center">
            <button type="button" class="btn btn-primary" onclick="search()" >Cari</button>
          </div>
        </div>
      </div>
    </section>

    <div class="contain">
    <h2>books that i need <i class="fa fa-star" id="starcounter" style="color:yellow"></i> : <span
            class="count">0</span></h2>
    <div class="table-responsive">
        <table class="table table-sm">
            <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th></th>
                <th scope="col">Book Title</th>
                <th scope="col">Authors</th>
                <th scope="col">P.Date</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
  </div>
  </body>

  <script>
  var counter =0;
function checkLike(){
  $.ajax({
        type : 'GET',
        url : 'lab_6/get_like',
        dataType : 'json',
        success : function(data) {
               for(var i=1; i<=data.message.length; i++) {
                    console.log(data.message[i]);
                    var id = data.message[i-1];
                    var td = document.getElementsByName(id)[0];
                    if(typeof td !== 'undefined'){
                        td.className='fas fa-star clicked';
                        td.style.color='yellow';
                    }

                   $('.count').html(data.message.length);

                }
                $('tbody').html(print);
        }
    });
};

$(document).on('click touchstart', '#star', function() {
        var id=$(this).attr("name");
        var ini = $(this);
         if( ini.hasClass('clicked') ) {
            $.ajax({
         url: "lab_6/unlike",
        type: "POST",
        data: {
            id: id,
        },
        success: function(result) {
            counter=result.message;
            ini.removeClass('clicked');
            ini.css("color","rgba(150,150,150,0.5);");
            $('.count').html(counter);
        },
        error : function (errmsg){
            alert("Something is wrong");
        }
    });

        } else {
             $.ajax({
         url: "lab_6/like",
        type: "POST",
        data: {
            id: id,
        },
        success: function(result) {
            counter=result.message;
            ini.addClass('clicked');
            ini.css("color","yellow");
            $('.count').html(counter);

        },
        error : function (errmsg){
            alert("Something is wrong");
        }
    });


        }




    });

</script>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="{% static "js/firstJavascript.js" %}"> </script>
</html>

lab_6/templates/choice.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/coverageLab.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <title id="Judul">Animusity | Log in</title>
  </head>


<body>
  <div class="h-100 row align-items-center">
        <div class="col-sm-12">
            <center>
              <a style="color: black;font-size: 40px;" href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
            </center>
        </div>
  </div>
</body>



<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="{% static "js/firstJavascript.js" %}"> </script>
</html>

lab_6/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/coverageLab.css" %}">
    <link rel="stylesheet" href="{% static "js/firstJavascript.js" %}">

    <title id="Judul">Animusity | Home</title>
  </head>

  <body>

    <!-- Ini bagian intro -->
    <section id="Headline">
      <div class= "container-fluid">
        <div class="jumbotron bg-transparent">
          <h1 class="display-4 text-center">Hello, Apa Kabar?</h1>
          <p class="lead text-center">Bagaimana harimu? Yuk ceritakan disini!</p>
          <hr class="my-4">
          <div class= "container text-center">
            <a class="btn btn-dark btn-md" href='{% url 'lab_6:profile' %}' role="button">Profile saya!</a>
          </div>
        </div>
      </div>
    </section>
    <!-- akhir bagian intro -->

    <!-- ini start form -->
    <section class= "formulir">
      <div class = "container">
        <form id="form" method="POST" action='{% url 'lab_6:home' %}'>
          <div class = "form-row">
            <div class="form-group col-md-12">
              {% csrf_token %}
              {{ form }}
            <input id="submit" type="submit" class="btn btn-dark btn-md btn-info" value="Post!">
            </div>
          </div>
        </form>
      </div>
    </section>
    <!-- ini akhir form -->

    <!-- ini awal dari iterasi object -->
    <section class="container">
      <div class="container">
        <div class ="row">
          {% for i in activity %}
            <div class ="col-sm-4 text-center">
              <h2> {{i.title}}</h2>
              <p> {{i.desc}} </p>
              <p> {{i.date}}</p>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
    <!-- ini akhir iterasi object -->




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

lab_6/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/coverageLab.css" %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <title>Irfanamrl | Profile</title>
  </head>

  <!-- last jumbotron -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
          <h1 class="display-4 text-center">Thanks for taking the time to reach out. <br>Subscribe, and let's be friends</h1>
        </div>
      </div>
    </section>
    <!-- akhir jumbotron -->


    <!-- ini start form -->
    <div class="container">
      <div class="form">
        <div class="element">
              {% csrf_token %}
                <p>Nama:
                    {{ form.nama_pendaftar }} </p>
                <p>Email:
                    {{ form.email_pendaftar }} </p>
                <p>Password
                    {{ form.password_pendaftar }} </p>
                <div  id='statusForm'>
                </div>
                <div class="container text-center">
                  <button type="submit" class="btn btn-outline-warning btn-lg" id='submit'>Submit</button>
                </div>
        </div>
      </div>
    </div>
    </section>
    <!-- ini akhir form -->

    <!-- ini start list subscriber -->
    <section class="container">
      <div class="col-md-12">
        <section id="listSubscriber">
        </section>
      </div>
    </section>

    <!-- ini waste of space -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
        </div>
      </div>
    </section>
    <!-- ini akhir waste of space -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static "js/firstJavascript.js" %}"> </script>
    </html>

lab_6/templates/profile.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/coverageLab.css" %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



    <title>Irfanamrl | Profile</title>
  </head>

  <body class="profilePage">
  <section class="bagian1">
    <div class = "container">
      <div class = "jumbotron bg-transparent" id="backgroundFirst">
        <h1 class = "text-center" id="judulProfile">Profile</h1>
        <div class="container text-center">
          <button type="button" class="btn btn-dark" id="button">Change Theme</button>
        </div>
      </div>
    </div>
  </section>

  <section class="bagian2">
    <div class = "container">
      <div class = "jumbotron bg-transparent">
        <div class="container">
          <div class="row">
            <div class="col text-right">
              <img src="https://scontent-sin2-2.xx.fbcdn.net/v/t1.0-9/22780166_1847280418634923_3057895947038492812_n.jpg?_nc_cat=111&_nc_ht=scontent-sin2-2.xx&oh=45271d0f909094239fe87ea72daecc3b&oe=5C7D3E28"
              alt="fotonya irfan" id="photoProfile" width="200">
            </div>
            <div class="col" id="profileDesc">
              <p class="profileDesc"> Nama:<br>Muhammad Irfan Amrullah </p>
              <p class="profileDesc"> NPM :<br>1706039585 </p>
              <p class="profileDesc"> Alamat:<br> Jl Pancoran Barat IX G </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="bagian3 container text-center">
    <div id="accordion">
      <h3>Pengalaman Organisasi/Kepanitiaan</h3>
      <div>
        <p>Saya sudah banyak ikut organisasi dan kepanitiaan. Dimulai dari Pemira Fasilkom 2017,
        kemudian akademis BETIS 2018, hingga Suara Mahasiswa</p>
        </div>
        <h3>Aktivitas</h3>
        <div>
          <p>Sekarang sedang sibuk menjadi mentor PMB Fasilkom 2018 yang baik</p>
        </div>
        <h3>Prestasi</h3>
        <div>
          <p>untuk prestasi, saya belum berprestasi sebanyak yang lain </p>
          </div>
        </div>
  </section>

  <script>
  $("#accordion").accordion();
  </script>

  <div class="se-pre-con"></div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
    <script src= "{% static "js/firstJavascript.js" %}" rel="script" type="text/javascript"> </script>
  </body>
</html>